name: wordit
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  csv_reader: ^1.0.2
  flutter_svg: ^0.18.0
  flip_card: ^0.4.4
  excel: ^1.1.0
  transparent_image: ^1.0.0
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.2.0
  path: ^1.5.1

flutter:
  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: svg_fonts/MyFlutterApp.ttf
    - family: Custom
      fonts:
        - asset: svg_fonts/Custom.ttf

  assets:
    - res/
    - images/
    - images/svg/
    - images/word_images/
